const keyMirror = require("keymirror");

module.exports.siteTypes = {
  ES: "Estuary",
  "FA-DV": "Diversion",
  GL: "Glacier",
  LK: "Lake",
  OC: "Ocean",
  "OC-CO": "Ocean Coastal",
  SP: "Spring",
  ST: "Stream",
  "ST-CA": "Canal",
  "ST-TS": "Tides"
};

module.exports.siteParams = keyMirror({
  agency_cd: null,
  site_no: null,
  station_nm: null,
  dec_lat_va: null,
  dec_long_va: null,
  country_cd: null,
  tz_cd: null,
  "state_cd": null,
  "district_cd ": null,
  "county_cd": null,
  "site_tp_cd": null,
});

module.exports.stateFipsCode = {
  "01": "Alabama",
  "02": "Alaska",
  "04": "Arizona",
  "05": "Arkansas",
  "06": "California",
  "08": "Colorado",
  "09": "Connecticut",
  "10": "Delaware",
  "11": "District of Columbia",
  "12": "Florida",
  "13": "Geogia",
  "15": "Hawaii",
  "16": "Idaho",
  "17": "Illinois",
  "18": "Indiana",
  "19": "Iowa",
  "20": "Kansas",
  "21": "Kentucky",
  "22": "Louisiana",
  "23": "Maine",
  "24": "Maryland",
  "25": "Massachusetts",
  "26": "Michigan",
  "27": "Minnesota",
  "28": "Mississippi",
  "29": "Missouri",
  "30": "Montana",
  "31": "Nebraska",
  "32": "Nevada",
  "33": "New Hampshire",
  "34": "New Jersey",
  "35": "New Mexico",
  "36": "New York",
  "37": "North Carolina",
  "38": "North Dakota",
  "39": "Ohio",
  "40": "Oklahoma",
  "41": "Oregon",
  "42": "Pennsylvania",
  "44": "Rhode Island",
  "45": "South Carolina",
  "46": "South Dakota",
  "47": "Tennessee",
  "48": "Texas",
  "49": "Utah",
  "50": "Vermont",
  "51": "Virginia",
  "53": "Washington",
  "54": "West Virginia",
  "55": "Wisconsin",
  "56": "Wyoming",
  "60": "American Samoa",
  "66": "Guam",
  "69": "Northern Marianas",
  "72": "Puerto Rico",
  "74": "U.S. Minor Outlying Islands",
  "78": "Puerto Rico"
}

module.exports.countyFipsCode = {
  "1": "Adjuntas Municipio",
  "3": "Aguada Municipio",
  "5": "Aguadilla Municipio",
  "6": "Cibola County",
  "7": "Aguas Buenas Municipio",
  "9": "Aibonito Municipio",
  "10": "St. Croix Island",
  "11": "Anasco Municipio",
  "12": "La Paz County",
  "13": "Arecibo Municipio",
  "14": "Broomfield County",
  "15": "Arroyo Municipio",
  "16": "Aleutians West Census Area",
  "17": "Barceloneta Municipio",
  "19": "Barranquitas Municipio",
  "20": "St. John Island",
  "21": "Bayamon Municipio",
  "23": "Cabo Rojo Municipio",
  "25": "Caguas Municipio",
  "27": "Camuy Municipio",
  "28": "Los Alamos County",
  "29": "Canovanas Municipio",
  "30": "St. Thomas Island",
  "31": "Carolina Municipio",
  "33": "Catano Municipio",
  "35": "Cayey Municipio",
  "36": "Charles City County",
  "37": "Ceiba Municipio",
  "39": "Ciales Municipio",
  "40": "Swains Island",
  "41": "Cidra Municipio",
  "43": "Coamo Municipio",
  "45": "Comerio Municipio",
  "47": "Corozal Municipio",
  "49": "Culebra Municipio",
  "50": "Western District",
  "51": "Dorado Municipio",
  "53": "Fajardo Municipio",
  "54": "Florida Municipio",
  "55": "Guanica Municipio",
  "57": "Guayama Municipio",
  "59": "Guayanilla Municipio",
  "60": "Bristol Bay Borough",
  "61": "Guaynabo Municipio",
  "63": "Gurabo Municipio",
  "65": "Hatillo Municipio",
  "67": "Hormigueros Municipio",
  "68": "Denali Borough",
  "69": "Humacao Municipio",
  "70": "Dillingham Census Area",
  "71": "Isabela Municipio",
  "73": "Jayuya Municipio",
  "75": "Juana Diaz Municipio",
  "77": "Juncos Municipio",
  "78": "Menominee County",
  "79": "Lajas Municipio",
  "81": "Lares Municipio",
  "83": "Las Marias Municipio",
  "85": "Las Piedras Municipio",
  "86": "Miami-Dade County",
  "87": "Loiza Municipio",
  "89": "Luquillo Municipio",
  "90": "Fairbanks North Star Borough",
  "91": "Manati Municipio",
  "93": "Maricao Municipio",
  "95": "Maunabo Municipio",
  "97": "Mayaguez Municipio",
  "99": "Moca Municipio",
  "100": "Rota Municipality",
  "101": "Morovis Municipio",
  "103": "Naguabo Municipio",
  "105": "Naranjito Municipio",
  "107": "Orocovis Municipio",
  "109": "Patillas Municipio",
  "110": "Saipan Municipality",
  "111": "Penuelas Municipio",
  "113": "Ponce Municipio",
  "115": "Quebradillas Municipio",
  "117": "Rincon Municipio",
  "119": "Rio Grande Municipio",
  "120": "Tinian Municipality",
  "121": "Sabana Grande Municipio",
  "122": "Kenai Peninsula Borough",
  "123": "Salinas Municipio",
  "125": "San German Municipio",
  "127": "San Juan Municipio",
  "129": "San Lorenzo Municipio",
  "130": "Ketchikan Gateway Borough",
  "131": "San Sebastian Municipio",
  "133": "Santa Isabel Municipio",
  "135": "Toa Alta Municipio",
  "137": "Toa Baja Municipio",
  "139": "Trujillo Alto Municipio",
  "141": "Utuado Municipio",
  "143": "Vega Alta Municipio",
  "145": "Vega Baja Municipio",
  "147": "Vieques Municipio",
  "149": "Villalba Municipio",
  "150": "Kodiak Island Borough",
  "151": "Yabucoa Municipio",
  "153": "Yauco Municipio",
  "155": "Pulaski County",
  "157": "Rappahannock County",
  "159": "Richmond County",
  "161": "Roanoke County",
  "163": "Rockbridge County",
  "164": "Lake and Peninsula Borough",
  "165": "Rockingham County",
  "167": "Russell County",
  "169": "Scott County",
  "170": "Matanuska-Susitna Borough",
  "171": "Shenandoah County",
  "173": "Smyth County",
  "175": "Southampton County",
  "177": "Spotsylvania County",
  "179": "Stafford County",
  "180": "Nome Census Area",
  "181": "Surry County",
  "183": "Sussex County",
  "185": "Tazewell County",
  "186": "Ste. Genevieve County",
  "187": "Warren County",
  "188": "Northwest Arctic Borough",
  "189": "Hale County",
  "191": "Washington County",
  "193": "Westmoreland County",
  "195": "Wise County",
  "197": "Wythe County",
  "198": "Prince of Wales-Hyder Census Area",
  "199": "York County",
  "201": "Harris County",
  "203": "Harrison County",
  "205": "Hartley County",
  "207": "Haskell County",
  "209": "Hays County",
  "211": "Hemphill County",
  "213": "Henderson County",
  "215": "Hidalgo County",
  "217": "Hill County",
  "219": "Hockley County",
  "220": "Sitka City and Borough",
  "221": "Hood County",
  "223": "Hopkins County",
  "225": "Houston County",
  "227": "Howard County",
  "229": "Hudspeth County",
  "230": "Skagway Municipality",
  "231": "Hunt County",
  "233": "Hutchinson County",
  "235": "Irion County",
  "237": "Jack County",
  "239": "Jackson County",
  "240": "Southeast Fairbanks Census Area",
  "241": "Jasper County",
  "243": "Jeff Davis County",
  "245": "Jefferson County",
  "247": "Jim Hogg County",
  "249": "Jim Wells County",
  "251": "Johnson County",
  "253": "Jones County",
  "255": "Karnes County",
  "257": "Kaufman County",
  "259": "Kendall County",
  "261": "Kenedy County",
  "263": "Kent County",
  "265": "Kerr County",
  "267": "Kimble County",
  "269": "King County",
  "270": "Wade Hampton Census Area",
  "271": "Kinney County",
  "273": "Kleberg County",
  "275": "Knox County",
  "277": "Lamar County",
  "279": "Lamb County",
  "281": "Lampasas County",
  "282": "Yakutat City and Borough",
  "283": "La Salle County",
  "285": "Lavaca County",
  "287": "Lee County",
  "289": "Leon County",
  "290": "Yukon-Koyukuk Census Area",
  "291": "Liberty County",
  "293": "Limestone County",
  "295": "Lipscomb County",
  "297": "Live Oak County",
  "299": "Llano County",
  "300": "Midway Islands",
  "301": "Loving County",
  "303": "Lubbock County",
  "305": "Lynn County",
  "307": "McCulloch County",
  "309": "McLennan County",
  "311": "McMullen County",
  "313": "Madison County",
  "315": "Marion County",
  "317": "Martin County",
  "319": "Mason County",
  "321": "Matagorda County",
  "323": "Maverick County",
  "325": "Medina County",
  "327": "Menard County",
  "329": "Midland County",
  "331": "Milam County",
  "333": "Mills County",
  "335": "Mitchell County",
  "337": "Montague County",
  "339": "Montgomery County",
  "341": "Moore County",
  "343": "Morris County",
  "345": "Motley County",
  "347": "Nacogdoches County",
  "349": "Navarro County",
  "351": "Newton County",
  "353": "Nolan County",
  "355": "Nueces County",
  "357": "Ochiltree County",
  "359": "Oldham County",
  "361": "Orange County",
  "363": "Palo Pinto County",
  "365": "Panola County",
  "367": "Parker County",
  "369": "Parmer County",
  "371": "Pecos County",
  "373": "Polk County",
  "375": "Potter County",
  "377": "Presidio County",
  "379": "Rains County",
  "381": "Randall County",
  "383": "Reagan County",
  "385": "Real County",
  "387": "Red River County",
  "389": "Reeves County",
  "391": "Refugio County",
  "393": "Roberts County",
  "395": "Robertson County",
  "397": "Rockwall County",
  "399": "Runnels County",
  "401": "Rusk County",
  "403": "Sabine County",
  "405": "San Augustine County",
  "407": "San Jacinto County",
  "409": "San Patricio County",
  "411": "San Saba County",
  "413": "Schleicher County",
  "415": "Scurry County",
  "417": "Shackelford County",
  "419": "Shelby County",
  "421": "Sherman County",
  "423": "Smith County",
  "425": "Somervell County",
  "427": "Starr County",
  "429": "Stephens County",
  "431": "Sterling County",
  "433": "Stonewall County",
  "435": "Sutton County",
  "437": "Swisher County",
  "439": "Tarrant County",
  "441": "Taylor County",
  "443": "Terrell County",
  "445": "Terry County",
  "447": "Throckmorton County",
  "449": "Titus County",
  "451": "Tom Green County",
  "453": "Travis County",
  "455": "Trinity County",
  "457": "Tyler County",
  "459": "Upshur County",
  "461": "Upton County",
  "463": "Uvalde County",
  "465": "Val Verde County",
  "467": "Van Zandt County",
  "469": "Victoria County",
  "471": "Walker County",
  "473": "Waller County",
  "475": "Ward County",
  "477": "Washington County",
  "479": "Webb County",
  "481": "Wharton County",
  "483": "Wheeler County",
  "485": "Wichita County",
  "487": "Wilbarger County",
  "489": "Willacy County",
  "491": "Williamson County",
  "493": "Wilson County",
  "495": "Winkler County",
  "497": "Wise County",
  "499": "Wood County",
  "501": "Yoakum County",
  "503": "Young County",
  "505": "Zapata County",
  "507": "Zavala County",
  "510": "Alexandria city",
  "515": "Bedford city",
  "520": "Bristol city",
  "530": "Buena Vista city",
  "540": "Charlottesville city",
  "550": "Chesapeake city",
  "570": "Colonial Heights city",
  "580": "Covington city",
  "590": "Danville city",
  "595": "Emporia city",
  "600": "Fairfax city",
  "610": "Falls Church city",
  "620": "Franklin city",
  "630": "Fredericksburg city",
  "640": "Galax city",
  "650": "Hampton city",
  "660": "Harrisonburg city",
  "670": "Hopewell city",
  "678": "Lexington city",
  "680": "Lynchburg city",
  "683": "Manassas city",
  "685": "Manassas Park city",
  "690": "Martinsville city",
  "700": "Newport News city",
  "710": "Norfolk city",
  "720": "Norton city",
  "730": "Petersburg city",
  "735": "Poquoson city",
  "740": "Portsmouth city",
  "750": "Radford city",
  "760": "Richmond city",
  "770": "Roanoke city",
  "775": "Salem city",
  "790": "Staunton city",
  "800": "Suffolk city",
  "810": "Virginia Beach city",
  "820": "Waynesboro city",
  "830": "Williamsburg city",
  "840": "Winchester city"
};